# Generated by Django 3.0.8 on 2020-08-12 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Langage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('H', 'HOMMME'), ('F', 'FEMME')], default='H', max_length=10, verbose_name='GENRE')),
                ('experence', models.CharField(choices=[('debutant', 'DEBUTANT'), ('intermediaire', 'INTERMEDIAIRE'), ('expert', 'EXPERT')], max_length=50)),
                ('wht', phonenumber_field.modelfields.PhoneNumberField(help_text='+225xxxxxxxx', max_length=128, region=None, verbose_name='Contact WhatsApp')),
                ('pays', django_countries.fields.CountryField(max_length=2)),
                ('ville', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='upload_avatar')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='upload_profile')),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('langages', models.ManyToManyField(to='users.Langage', verbose_name='Preciser vos Langages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'abonne',
                'verbose_name_plural': 'ABONNES',
            },
        ),
    ]
