# Generated by Django 3.0.8 on 2020-08-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cours de base', max_length=250)),
                ('description', models.CharField(default='Cours de base', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.CharField(max_length=1000)),
                ('content', models.URLField()),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Categorie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.CharField(max_length=1000)),
                ('content', models.BinaryField()),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Categorie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.CharField(max_length=1000)),
                ('content', models.BinaryField()),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Categorie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
